### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by Mischback** [Mischback/colorizer#14]
Several tools should be in place to support the development:

- **NodeJS**
  - [x] ``package.json`` This is not a NodeJS module, so no complete ``package.json`` is required. Provide some minimal meta information, but the focus is tracking dependencies here.
  - [x] **Linting**
    - [x] ``lint-staged`` and ``simple-git-hooks`` (#15)
    - [x] ``prettier`` (#15)
    - [x] ``eslint``, setup for TypeScript (#16)
    - [x] *typechecking* using ``tsc`` (#16)
    - [x] ``stylelint`` (see [``.stylelintrc`` @ mischback.de](https://github.com/Mischback/mischback.de/blob/development/.stylelintrc.yaml))
      - [x] ``stylelint-config-standard-scss`` (#26)
      - [x] ``stylelint-config-sass-guidelines`` (#26)
      - [x] ``stylelint-config-property-sort-order-smaccs`` (#26)
      - [x] ~~``stylelint-config-prettier``~~ **Not longer required!**
    - [ ] https://github.com/ai/size-limit
  - [x] **TypeScript** (see #11)
    - [x] ``typescript`` / ``tsc`` (#16)
    - [x] ``Rollup`` (#16)
    - [x] ~~testing (``jest``)?~~ **Skipped for now!** See #19 
  - [x] **SASS** (see #18)
    - [x] ``sass`` (#26)
    - [x] ``postcss`` (#26)
- **GitHub Actions**
  - [ ] ``Dependabot``
    - [ ] ``gh-actions`` (monthly)
    - [ ] ``npm`` (monthly)
    - [ ] run against ``development`` branch
    - [ ] apply *auto-approving*
  - [ ] *development workflow*
    - [x] running linters on sources (TS and SASS) (#15)
    - [x] ~~running tests on TS sources? ``coveralls``?~~ **Skipped for now!** See #19 
    - [ ] running build with ``Rollup`` (just to verify that this is working!)
  - [ ] *release workflow* (#30)
