### ISSUE TITLE
``v2`` Feature List

### ISSUE THREAD

**Issue by Mischback** [Mischback/colorizer#35]
This is a meta issue for the features that should be provided with [``v2``](https://github.com/Mischback/colorizer/milestone/1). It is **not meant** to track everything related to the [v2 milestone](https://github.com/Mischback/colorizer/milestone/1), but instead be a backlog of required features / functions.

- [ ] **Color Input**
  - [x] ``RGB`` with ``R``, ``G`` and ``B`` in range ``[0..255]`` (#20)
  - [ ] ``RGB`` with **hexadecimal** input (*output* already implemented in #53)
  - [x] ``RGB`` with ``HSL`` notation (#24)
  - [x] ``RGB`` with ``HWB`` notation (#24)
  - [ ] ``CIELab`` with ``L`` in range ``[0..100]`` and ``a``/``b`` in range ``[-125..125]``
  - [ ] ``CIELab`` with ``CIELCH`` notation with ``L`` in range ``[0..100]``, ``C`` in range ``[0..150]`` and ``H`` specified in ``deg`` (``[0..360[``).
  - [ ] ``OkLab`` with ``L`` in range ``[0..1]`` and ``a``/``b`` in range ``[-0.4..0.4]``
  - [x] ``OkLab`` with ``OkLCH`` notation with ``L`` in range ``[0..1]``, ``C`` in range ``[0..0.4]`` and ``H`` specified in ``deg`` (``[0..360[``) (#20, #36)
  - [ ] ``OkHSL``
    - [ ] Ref: https://bottosson.github.io/posts/colorpicker/
    - [ ] Source: https://github.com/bottosson/bottosson.github.io/tree/master/misc/colorpicker
  - [ ] ``OkHSV``
    - [ ] Ref: https://bottosson.github.io/posts/colorpicker/
    - [ ] Source: https://github.com/bottosson/bottosson.github.io/tree/master/misc/colorpicker
- [ ] **Palette Management** (genearal implementation: #37)
  - [x] store palette items in ``IndexedDB`` of the browser (related: #17)
  - [x] *sort* the palette by drag'n'drop (#40 / #43)
  - [x] remove items from the palette (#37)
  - [ ] *clear* / *reset* palette
    - [ ] *confirmation dialogue* required/desired?
  - [ ] *export* to ``JSON``
  - [ ] *import* from ``JSON``
- [x] **Contrast Grid**
  - [x] the *main output*!
  - [x] contrast ratio
  - [x] contrast classification (WCAG2.0)
  - [x] is this working without converting to ``RGB``? (see #34)
  - [x] allow sorting of the palette (by drag'n'drop) from the grid visualization (related: #40 / #43)
    - [x] sort rows
    - [x] sort columns (fix this in #43)
- [ ] Overall layout / interface
  - [ ] be as accessible as possible!
    - References
      - https://a11y-101.com/
      - https://www.magentaa11y.com/
    - **Already known issues**
      - *drag'n'drop* sorting of the palette has no alternative for non-mouse users
      - *drag'n'drop* is currently not working on touch devices, but there's a polyfill
  - [ ] tabs?
    - [x] palette
    - [x] color add form
    - [x] contrast grid
    - [ ] (settings)
    - [ ] (about)
