### ISSUE TITLE
Palette Management

### ISSUE THREAD

**Issue by Mischback** [Mischback/colorizer#37]
## Implementation Idea

- [x] split the **engine** from the **visualization**
  - [x] ``ColorizerPalette`` is the **engine**
    - [x] manages the *palette* **internally**
      - [x] **add** ``ColorizerPaletteItem``
      - [x] **remove** ``ColorizerPaletteItem``
      - [x] **update** ``ColorizerPaletteItem``
    - [x] implements the **Observable** part of the *Observer pattern*
    - [x] interacts with the *database abstraction*
  - [x] ``ColorizerPaletteInterface`` is the **visualization**
    - [x] **[REFACTOR]** rename to ``ColorizerPaletteIO``
    - [x] handles all interaction with the ``DOM``
      - [x] visualize palette items by creating the required ``DOM`` elements
      - [x] *button* to remove a palette item
      - [x] drag'n'drop sorting of palette items (#40)

## Todo

- [x] create ``ColorizerPaletteItem`` class
  - [x] instances need a *unique identifier* throughout their life span
    - I don't really want to mess with this low-level stuff, better to leave this to ``IndexedDB``, which might actually be possible
    - **Leave it to ``IndexedDB``**:
      - [Structuring the Database@MDN](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#structuring_the_database) suggests, that when a ``keyPath`` and a ``keyGenerator`` are used on the store, keys are actually managed/provided/assigned by the ``IndexedDB``. The [W3C spec](https://www.w3.org/TR/IndexedDB/#key-generator-construct) provides some more technical details. As far as I understand it, the *auto-generated keys* are automatically deconflicted.
      - when creating an actually **new instance**, let the *unique identifier attribute* be ``undefined``. Hopefully it is provided when the instance is stored.
      - **BUT: What to do in the meantime?!**
    - **Self-managed identifier**:
      - Idea: Use the ``IndexedDB``'s ``store`` with a ``keyPath`` ``paletteItemID``
      - determine a ``PaletteItem``'s ``paletteItemID`` in the ``constructor()``, e.g. as a hash of the ``X``, ``Y`` and ``Z`` coordinates.
      - additional benefit: no duplicate colors!
- [x] create ``ColorizerPalette`` class
  - [x] *Observer* pattern!
    - [x] ``src/script/colorizer/lib/types.ts``: **rename** ``IColorizerObserver`` to ``IColorizerColorObserver``
    - [x] ``src/script/colorizer/lib/types.ts``: **rename** ``IColorizerSubject`` to ``IColorizerColorObservable``
    - [x] ``src/script/colorizer/lib/types.ts``: **create** ``IColorizerPaletteObserver``
    - [x] ``src/script/colorizer/lib/types.ts``: **create** ``IColorizerPaletteObservable``
  - [x] add new ``ColorizerPaletteItem`` to ``ColorizerPalette`` instance
  - [x] remove ``ColorizerPaletteItem`` from ``ColorizerPalette`` instance

## Resources

- **Class Serialization / Deserialization**
  - https://oooops.dev/2022/09/30/serializing-and-de-serializing-es6-class-instances-recursively/
  - https://medium.com/@aems/one-mans-struggle-with-typescript-class-serialization-478d4bbb5826
  - https://stackoverflow.com/questions/16261119/typescript-objects-serialization
  - https://stackoverflow.com/questions/71004835/serializing-an-object-in-typescript-with-methods-and-a-cyclical-reference-graph
  - https://stackoverflow.com/questions/73808039/typescript-class-customize-json-serialization-deserialization
  - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

**Comment by Mischback** [comment]
## Dry Coded

```typescript
class ColorizerPaletteItem {
  private color: ColorizerColor;
  private sorting: number;
  private id: number;
}
```

**Comment by Mischback** [comment]
```
src/
├── index.html
├── script
│   ├── colorizer
│   │   ├── interface
│   │   │   ├── color-form
│   │   │   │   ├── form.ts
│   │   │   │   ├── index.ts
│   │   │   │   └── input-methods.ts
│   │   │   └── palette.ts
│   │   └── lib
│   │       ├── color.ts
│   │       └── types.ts
│   ├── colorizer.ts
│   └── utility
│       ├── color-processing.ts
│       └── index.ts
└── style
    ├── abstracts
    │   └── __abstracts.scss
    ├── base
    │   ├── __base.scss
    │   ├── button.scss
    │   ├── hide-visually.scss
    │   └── min-reset.scss
    ├── components
    │   ├── color-form
    │   │   ├── button.scss
    │   │   ├── __color-form.scss
    │   │   ├── input-text-range.scss
    │   │   └── tooltip.scss
    │   └── __components.scss
    ├── layouts
    │   └── __layouts.scss
    └── style.scss

12 directories, 22 files
```

**Comment by Mischback** [comment]
## Dry Coding

```typescript
class ColorizerPaletteItem {
  private color: ColorizerColor;
  private sorting: number;
  private paletteItemId: string;

  public constructor(color: ColorizerColor, sorting?: number) {
    this.color = color;

    if (sorting !== undefined) {
      this.sorting = sorting;
    } else {
      this.sorting = 999;
    }

    console.debug(this.color);
    console.debug(this.sorting);
  }
}
```
