### ISSUE TITLE
Replace ``SortableJS``

### ISSUE THREAD

**Issue by Mischback** [Mischback/colorizer#43]
During implementation of #40, the actual drag'n'drop operation is handled with [SortableJS](https://github.com/SortableJS/Sortable). However, this adds around 40 - 50kB to the bundle size, which is *kind of not acceptable*.

After finishing the initial implementation of the **contrast grid**, which should also allow drag'n'drop operations, ``SortableJS`` should be replaced, because I feel like the app is using just a minimal subset of its functions.

``v1`` / the original implementation had its own drag'n'drop logic already implemented. Should be easily adaptable.

**Comment by Mischback** [comment]
> `v1` / the original implementation had its own drag'n'drop logic already implemented. Should be easily adaptable.

**Nope**

## Problem A

Most existing Drag'n'Drop libraries are pure JS implementations, that do not use HTML5's native drag'n'drop API.

This means they are required to implement lots of stuff and add quite some size to a bundle.


## Problem B

HTML5's native API requires the draggable elements to have an attribute ``draggable="true"``, which is basically fine. But as most of the elements that are meant to be draggable in Colorizer are dynamically created, this may cause some issues.

Possible solution: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

**Comment by Mischback** [comment]
```typescript
  dragOverHandler(evt) {
    console.debug("dragOver()");

    if (this.dropZone !== evt.target) {

      this.newIndex = this.getDraggableItemIndex(evt.target);
      this.dropZone = evt.target;

      if ((this.newIndex !== -1) && (this.newIndex !== this.oldIndex)) {
        evt.preventDefault();
      }
    }
  }
```

**Comment by Mischback** [comment]
## Dry Coding II

```typescript
class DragToOrder {
  constructor(container, draggableItemQuery) {
    this.container = container;
    this.itemQuery = draggableItemQuery;

    this.draggedItem = undefined;
    this.oldIndex = -1;
    this.dropZone = undefined;
    this.newIndex = -1;

    this.container.addEventListener(
      "dragstart",
      this.handlerDragStart.bind(this)
    );
    this.container.addEventListener("dragend", this.handlerDragEnd.bind(this));
    this.container.addEventListener(
      "dragover",
      this.handlerDragOver.bind(this)
    );
    this.container.addEventListener("drop", this.handlerDragDrop.bind(this));
    this.container.addEventListener(
      "dragenter",
      this.handlerDragEnter.bind(this)
    );
    this.container.addEventListener(
      "dragleave",
      this.handlerDragLeave.bind(this)
    );

    // Observe mutations of the container, in particular the addition of new
    // child elements.
    this.containerMutationObserver = new MutationObserver(
      this.containerMutationCallback.bind(this)
    );
    this.containerMutationObserver.observe(this.container, { childList: true });

    // Initial setup of the *draggable items*.
    this.prepareItems(this.getItems());
  }

  createItem(item) {
    console.debug("createItem()");

    if (item.getAttribute("draggable") === "true") {
      console.debug("Item is already draggable");
      return;
    }

    console.debug("Item must be processed");
    item.setAttribute("draggable", "true");
  }

  getItemIndex(item) {
    if (item === this.container) {
      throw new ItemNotFoundError("Item not found in container");
    }

    const itemIndex = Array.prototype.indexOf.call(this.getItems(), item);

    if (itemIndex === -1) {
      return this.getItemIndex(item.parentNode);
    }

    return itemIndex;
  }

  /**
   * Get a list of *draggable items*.
   *
   * This method uses ``querySelectorAll()`` with ``this.itemQuery`` to get
   * the list of items that are meant to be draggable.
   */
  getItems() {
    return this.container.querySelectorAll(this.itemQuery);
  }

  handlerDragStart(evt) {
    console.debug("handlerDragStart()");
    // console.debug(evt);

    let tmpIndex = -1;
    try {
      tmpIndex = this.getItemIndex(evt.target);
    } catch (err) {
      if (err.name === "ItemNotFoundError") {
        // console.debug("This is not the event handler you're looking for!");
        return;
      } else {
        throw err;
      }
    }

    if (this.container.contains(evt.target) === false) {
      console.warn("Should not be reached!");
      return;
    }

    // @ts-expect-error TS18047 Might be ``null``... Nope!
    evt.dataTransfer.effectAllowed = "move";

    // FIXME: Make the class name configurable!
    // evt.target.classList.add("currently-dragged");

    this.draggedItem = evt.target;
    this.oldIndex = tmpIndex;
  }

  handlerDragEnd(evt) {
    console.debug("handlerDragEnd()");
    // console.debug(evt);

    // FIXME: Make the class name configurable!
    // evt.target.classList.remove("currently-dragged");
  }

  handlerDragOver(evt) {
    // console.debug("handlerDragOver()");
    // console.debug(evt);

    let tmpIndex = -1;
    try {
      tmpIndex = this.getItemIndex(evt.target);
    } catch (err) {
      if (err.name === "ItemNotFoundError") {
        this.newIndex = -1;
        this.dropZone = undefined;
        // console.debug("This is not the event handler you're looking for!");
        return;
      } else {
        throw err;
      }
    }

    if (this.dropZone !== evt.target) {
      this.newIndex = tmpIndex;
      this.dropZone = evt.target;
    }

    if (tmpIndex !== -1 && this.oldIndex !== -1 && this.newIndex !== this.oldIndex) {
      // console.debug("Identified a valid drop zone!");
      evt.preventDefault();
    }
  }

  handlerDragDrop(evt) {
    console.debug("handlerDragDrop()");
    // console.debug(evt);

    let tmpIndex = -1;
    try {
      tmpIndex = this.getItemIndex(evt.target);
    } catch (err) {
      if (err.name === "ItemNotFoundError") {
        console.debug("This is not the event handler you're looking for!");
        return;
      } else {
        throw err;
      }
    }

    // FIXME: Make the class name configurable!
    // this.dropZone.classList.remove("drop-target-hover");

    console.info(`oldIndex: ${this.oldIndex}, newIndex: ${this.newIndex}`);

    this.draggedItem = undefined;
    this.oldIndex = -1;
    this.dropZone = undefined;
    this.newIndex = -1;
  }

  handlerDragEnter(evt) {
    console.debug("handlerDragEnter()");
    // console.debug(evt);

    // FIXME: Make the class name configurable!
    // evt.target.classList.add("drop-target-hover");
  }

  handlerDragLeave(evt) {
    console.debug("handlerDragLeave()");
    // console.debug(evt);

    // FIXME: Make the class name configurable!
    // this.dropZone.classList.remove("drop-target-hover");
  }

  /**
   * Iterate a list of items that are meant to be *draggable*.
   *
   * @param itemList The list of items to process.
   *
   * Basically this makes sure to call ``createItem()`` an all items.
   */
  prepareItems(itemList) {
    console.debug("prepareItems()");

    itemList.forEach((item) => {
      this.createItem(item);
    });
  }

  /**
   * Prepare dynamically added *draggable items* for dragging operations.
   *
   * The *draggable items* might be added dynamically to the container, so
   * the required attributes and event handlers must be added dynamically, too.
   *
   * Reference:
   * - https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver
   * - https://developer.mozilla.org/en-US/docs/Web/API/MutationRecord
   */
  containerMutationCallback(
    mutationList,
    _
  ) {
    for (const mutation of mutationList) {
      if (mutation.type !== "childList") {
        console.warn("Unexpected mutation type");
        continue;
      }

      this.prepareItems(mutation.addedNodes);
    }
  }
}
```

**Comment by Mischback** [comment]
## ToDo

- [x] ``prepareItems(itemList)`` => ``prepareItems()``
  - after fixing an issue in ``containerMutationCallback()``, ``prepareItems()`` is now only used with ``getItems()`` as input parameter, so the call to ``getItems()`` can be internalized *(again)*
- [x] get rid of ``createItem(item)``
  - ``createItem()`` is called in exactly one place, during ``prepareItems()``
  - no need to have a dedicated functions/method
- [x] documentation of type ``TDragToOrderDragResultCallback`` (part of the external interface)
- [x] documentation of ``DragToOrder`` class
  - [x] ``constructor`` parameters
  - [x] general class documentation
  - [x] at least the *purpose* of all methods
  - [x] keep track of the ``event.target`` in the event handler methods (is it the dragged element or the element under the cursor?!)
- [x] ``styleDropTargetHover`` is not applied to the correct element! It *should* always go to another item with ``draggable="true"``, these are assumed to be the drop targets. As of now, it might go to child elements of that item.
